image:
  repository: ghcr.io/progress44/chatterbox-api
  tag: latest
  pullPolicy: Always

service:
  port: 4123

tts:
  device: cuda
  maxTotalLength: "4000"
  maxChunkLength: "280"
  exaggeration: "0.5"
  cfgWeight: "0.5"
  temperature: "0.8"
  useMultilingualModel: "true"
  nvidiaVisibleDevices: all
  nvidiaDriverCapabilities: compute,utility
